#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';
// this handler is dump and not smart at all
class __DumpRequestHandler extends SockServer\StreamRequestHandler
{
    protected function handle()
    {
        $buf = '';
        if (false !== ($bytes = socket_recv($this->request, $buf, 8192, 0))) {
            echo "Read $bytes bytes from socket_recv(). Closing socket...";
        } else {
            echo "socket_recv() failed; reason: " . socket_strerror(socket_last_error($this->request)) . "\n";
        }

        echo $buf . "\n";
        echo "OK.\n\n";
    }
}

$server = new SockServer\TCPServer('127.0.0.1:2346', __DumpRequestHandler::class);
$server->handleRequest();